In [12]:
import numpy as np

In [13]:
a = np.array([1,2,3,4,5])# 1D array
print(a)

[1 2 3 4 5]


In [14]:
type(a)

numpy.ndarray

In [15]:
#Creating 2D array
a2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [16]:
#Creating 3D array
a3 = np.array([[[1,2,3],[4,5,6]],[[5,6,7],[8,9,10]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 5  6  7]
  [ 8  9 10]]]


In [17]:
print(a2.shape)#Methords
print(a2.ndim)
print(a2.dtype)

(2, 5)
2
int64


In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [21]:
np.random.randint(1,11, size=(2,3))

array([[ 3, 10, 10],
       [ 8,  7, 10]], dtype=int32)

In [22]:
x = np.array([[7,2,3],
              [2,5,2],
              [3,5,1]])
y= np.array([[1,8,3],
             [3,7,2],
             [2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [24]:
print(x*y)

[[ 7 16  9]
 [ 6 35  4]
 [ 6 25  3]]


In [23]:
print(x@y) #Matricx multiplication

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [25]:
np.dot(x,y) #Matrix multiplication

array([[19, 85, 34],
       [21, 61, 22],
       [20, 64, 22]])

In [26]:
x.prod()#product of all element of the array

np.int64(12600)

In [27]:
x.mean()#mean of all element

np.float64(3.3333333333333335)

In [28]:
y.mean()

np.float64(3.7777777777777777)

In [30]:
print (x)

[[7 2 3]
 [2 5 2]
 [3 5 1]]


In [31]:
x.mean( axis = 0) # column wise mean

array([4., 4., 2.])

In [35]:
y.mean(axis=1)# row wise mean

array([4.        , 4.        , 3.33333333])

In [36]:
print(x.sum())
print(x.std())
print(x.var())

30
1.8257418583505538
3.3333333333333335


In [37]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,25))#list quartile
print(np.percentile(a,50))#median
print(np.percentile(a,75))#3rd quartile

3.0
5.0
7.0


In [ ]:
b= np.random.randint(11,100,(4,4)) #make random number matrix in which we provide size
print(b)

[[78 67 95 99]
 [11 31 86 77]
 [20 42 18 31]
 [51 85 41 67]]


In [39]:
print('2X8')
print(b.reshape(2,8))
print('8X2')
print(b.reshape(8,2))

2X8
[[78 67 95 99 11 31 86 77]
 [20 42 18 31 51 85 41 67]]
8X2
[[78 67]
 [95 99]
 [11 31]
 [86 77]
 [20 42]
 [18 31]
 [51 85]
 [41 67]]


In [40]:
x = np.random.randint(1,11,(5,5))
print(x)

[[10  5  6  4  6]
 [ 3  2  7  8 10]
 [ 6  9  5 10  8]
 [ 8  2  5  3  1]
 [ 8  8  2  8 10]]


In [41]:
print(x[0])#1st row
print(x[0,1])#1st row 2nd column's first elemnet
print(x[-1])

print(x[:3])
print(x[3:])

[10  5  6  4  6]
5
[ 8  8  2  8 10]
[[10  5  6  4  6]
 [ 3  2  7  8 10]
 [ 6  9  5 10  8]]
[[ 8  2  5  3  1]
 [ 8  8  2  8 10]]
